name: example
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.2.0
  image_picker: ^0.7.5+3
  firebase_storage: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
